name: Triggers
on: 
  push:
    branches:
      - 'main*'

jobs:
  # Job name
  Trigger:
    runs-on: ubuntu-latest # github hosted runners
    steps:
      - name: Feature branch push
        run: echo "Feature branch push"